services:
    site.locale_listener:
        class: RumoACertificacaoPHP\SiteBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }